# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2014-2018
  project: Start
  version: 4.0
  release: 4.0.3
  latex_documents:
  - - Index
    - start.tex
    - Start TYPO3 Responsive!
    - Dirk Wildt (Die Netzmacher)
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...