conf.py:
  copyright: 2014-2017
  project: Start
  version: 2.6
  release: 2.6.0
  latex_documents:
  - - Index
    - start.tex
    - Start TYPO3 Responsive!
    - Dirk Wildt (Die Netzmacher)
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}